language: ruby
rvm:
  - 2.5
before_install:
  - gem update --system
  - gem install bundler
bundler_args: "--without demo_test_run"
services:
  - postgresql
before_script:
  - psql -c 'create database spectre_test;' -U postgres
addons:
  postgresql: "9.6"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD; docker build -t wearefriday/spectre .; docker push wearefriday/spectre; fi
