services:
  app:
    build: .
    ports:
     - "3000:3000"
    links:
     - db
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - DATABASE_URL=postgresql://postgres@db/spectre
      - DATABASE_USERNAME=spectre
      - POSTGRES_PASSWORD=somepassword
      - DOMAIN_NAME=app
      - PORT=:3000
      - PROTOCOL=http://
      - SECRET_KEY_BASE=a1b2c3d4e5f6789012345678901234567890123456789012345678901234567890123456789012345678901234567890
    volumes:
     - .:/app
    command: bash -c "rm -f /app/tmp/pids/*.pid && rake assets:precompile && rails server -p 3000"

  db:
    image: postgres:17
    ports:
     - "5432"
    volumes:
     - .:/app
     - .:/public
     - data-db:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=spectre
     - POSTGRES_PASSWORD=somepassword

volumes:
  data-db: {}
