default: &default
  adapter: postgresql
  encoding: unicode
  # Specify PostgreSQL version 14 for Heroku compatibility
  postgresql_version: '14'
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spectre_development

test:
  <<: *default
  database: spectre_test

production:
  <<: *default
  database: spectre_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] || ENV['DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
